fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "clenait.ste@gmail.com"
        sender_name: "mohammed.ph2@gmail.com"
